name: Send Parsed Webhook

on:
  issues:
    types: [opened]

jobs:
  send-custom-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Parse issue body and send webhook
      uses: actions/github-script@v6
      with:
        script: |
          const body = context.payload.issue.body;

          // Extract value after the keyword labels using regex
          // We assume the pattern is label + value without space, so split accordingly

          function extractValue(label, text) {
            const regex = new RegExp(label + '(.*?)(?=Company|How many parts per bed\\?|Material|STL File|$)', 's');
            const match = text.match(regex);
            return match ? match[1].trim().replace(/\n/g, ' ') : "";
          }

          // Extract fields based on your description
          const company = extractValue("Company", body);
          const parts = extractValue("How many parts per bed?", body);
          const material = extractValue("Material", body);
          const link = extractValue("STL File", body);

          const data = {
            company,
            parts,
            material,
            link
          };

          console.log('Parsed data:', data);

          // Send the data as JSON to your webhook endpoint
          const url = 'https://hooks.slack.com/triggers/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';

          await fetch(url, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
          });
